name: NFSN Deploy

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README*'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Test
      run: make test

    - name: Build
      run: |
        make build-nfsn
        mkdir -p protected
        mv main_nfsn protected/

    - name: Scripts
      run: |
        BEARER_TOKEN="${{ secrets.BEARER_TOKEN }}" make scripts-nfsn
        mv run.sh protected/

    - name: Deploy
      run: >
        sshpass -p "${{ secrets.NFSN_PASSWORD }}" rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete protected/ "${{ secrets.NFSN_USERNAME }}"@"${{ secrets.NFSN_HOSTNAME }}":/home/protected/

    - name: Restart Daemon
      run: |
        sleep 5
        echo "https://${{ vars.NFSN_SHORTNAME }}.nfshost.com/shutdown"
        curl -X POST -H 'Authorization: Bearer ${{ secrets.BEARER_TOKEN }}' 'https://${{ vars.NFSN_SHORTNAME }}.nfshost.com/shutdown'
